### ISSUE TITLE
"Success" needs a success message. Please?

### ISSUE THREAD

**Issue by iDGS** [edalzell/statamic-profiler-issues#6]
Seems like maybe this issue somehow got lost, so to recap:

Back in ye olde days of Raven, you could cue the user that updating a field in the form worked by injecting a "success" message onto the page. So something like "Updated OK." (or whatever) would be spiffy.  I imagine code at the top of the form might go something like this:
```
        {{ profiler:edit_form redirect="/member/update" files="true" }}
  {{ if error }}
    <p class="error">{{ error }}</p>
  {{ elseif success }}
    <p class="success">{{ success }}</p>
  {{ /if }}
...
```
(Forgive me if this is a repeat issue; I simply couldn't find it.)

**Comment by edalzell** [comment]
The variable is there, it is a boolean, use whatever message you like.
